# Generated by Django 3.2.25 on 2024-12-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_no', models.CharField(max_length=45)),
                ('item', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=45)),
                ('public_location', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'delivery',
                'managed': False,
            },
        ),
    ]
