# Generated by Django 3.2.25 on 2024-12-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_task', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'scheduling',
                'managed': False,
            },
        ),
    ]
